## Stage 1 : build with maven builder image
FROM eclipse-temurin:21-jdk AS build
WORKDIR /code

COPY mvnw /code/mvnw
COPY .mvn /code/.mvn
COPY pom.xml /code/
COPY src /code/src

RUN chmod +x mvnw
RUN ./mvnw -B package -DskipTests

## Stage 2 : create the docker final image
FROM eclipse-temurin:21-jre

WORKDIR /app
COPY --from=build /code/target/quarkus-app/ /app/

EXPOSE 8080

CMD ["java", "-jar", "/app/quarkus-run.jar", "-Dquarkus.http.host=0.0.0.0"]
